source 'https://rubygems.org'

gem 'rails', '3.2.13'

gem 'pg'

group :test, :development do
  gem 'rspec-rails'
  gem 'faker'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'database_cleaner'
  gem 'guard-rspec'
  gem 'factory_girl_rails'
end
