development:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: sketchy_overflow_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: sketchy_overflow_test
  pool: 5
  timeout: 5000